apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tb-node-license-pv-claim
  namespace: thingsboard
  labels:
    app: tb-node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi